--- #YAML:1.0
name:               XML-Writer-Simple
version:            0.06
abstract:           Create XML files easily!
author:
    - Alberto Simoes <ambs@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:      0
    XML::DT:         0.42
    XML::DTDParser:  2.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
